export const SET_TYPE_ITEMS = 'SET_TYPE_ITEMS';
export const FAILED_SET_TYPE_ITEMS = 'FAILED_SET_TYPE_ITEMS';



export const SET_SELECTOR_VALUE = 'SET_SELECTOR_VALUE';



export const SET_CART_VALUE = 'SET_CART_VALUE';


export const SET_UNIQUE_LINKS = 'SET_UNIQUE_LINKS';
export const FAILED_SET_UNIQUE_LINKS = 'FAILED_SET_UNIQUE_LINKS';

